### ISSUE TITLE
geom_boxjitter: can we skip drawing the jitter points?

### ISSUE THREAD

**Issue by tungmilan** [erocoar/ggpol#4]
Hello,

I want to keep only the half boxplot and replace the jitter points with the points from the [`ggbeeswarm`](https://github.com/eclarke/ggbeeswarm) package. Is it possible? Could you add an option to turn on/off the plotting of all the points?

In the example below, I can disable the color of all the jitter points but it leaves an empty space between the boxplot and the beeswarm.

Thanks!

``` r

library(ggplot2)
library(ggbeeswarm)
library(ggpol)

ggplot(iris, aes(y = Petal.Width)) + 
  geom_boxjitter(jitter.shape = NA, 
                 jitter.color = NA,
                 jitter.height = 0, 
                 jitter.width = 0,
                 outlier.color = NA, 
                 errorbar.draw = TRUE) +
  geom_quasirandom(
    aes(x = 1, color = Species),
    width = 0.25,
    size = 2, 
    groupOnX = TRUE, alpha = 0.7) +
  scale_color_brewer(palette = 'Set2') +
  theme_classic()
```

![](https://i.imgur.com/bO2T4vX.png)

<sup>Created on 2019-05-18 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by erocoar** [comment]
It's a bit more difficult than that because while only half the boxplot is shown, it takes up an entire factor on the scales together with the points. But I like the general idea so I am considering changing up the function arguments a bit. With  7958ee8  you can pass on a `Position` class (defaults to `PositionDodge`).

In this case:

```r
ggplot(iris, aes(y = Petal.Width)) +
  geom_boxjitter2(jitter.position = ggbeeswarm:::PositionQuasirandom, 
                  jitter.params = formals(position_quasirandom)) +
  theme_classic()
```
![Rplot](https://user-images.githubusercontent.com/16050768/57987721-c53f2680-7a85-11e9-9461-4b7d344740ca.png)

**Comment by tungmilan** [comment]
Thanks for the quick update! Can you color different species (as in my example) too?

**Comment by erocoar** [comment]
I have to think about how to implement that in a user-friendly way. I could imagine passing a vector to `jitter.color`, but I don't think it will be possible to use `scale_color_` for this. Will update later.

**Comment by erocoar** [comment]
Getting back to this: It seems rather pointless to implement without also properly implementing `color` (, `fill`, `alpha`, `shape`) scales. Right now the geom calls `pointsGrob` directly. I'll need to do some more reading into the source code to see how I can implement that. Potentially with a new `geom_half_half`.

**Comment by tungmilan** [comment]
@erocoar : thanks for the update!

**Comment by tungmilan** [comment]
@erocoar : Hi this is off topic but how can you control the width of the boxplot? I tried `width = ...` but it changed the width of the point spreading. Thanks!

**Comment by erocoar** [comment]
Okay so for the `geom_quasirandom` issue, could you check out whether `geom_half_boxplot` from [gghalves](https://github.com/erocoar/gghalves) package works for you and otherwise file an issue there with the specific functionality you'd like to see? It should work for your example, but probably not when you have multiple `x` values.

For the width, it should (and does for me) change the width of both boxplot and point spreading. Is that the case for you too?

**Comment by tungmilan** [comment]
Great! Thanks for working on this! I'll try it as soon as I can
